{% set name = "kastore" %}
{% set version = "0.2.2" %}
{% set sha256 = "48d19734eba2dd07490b147d73fce392bbe4415448dffac01a2a0dbf7c6754ee" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - kastore=kastore.__main__:main
  # We need C99 and the Windows compilers before py35 won't work.
  skip: True  # [win and py<35]

# Following the guidance here for building against numpy:
# https://conda-forge.org/docs/meta.html#building-against-numpy
requirements:
  build:
    - {{ compiler('c') }}
  host:
    - setuptools
    - python
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - six
    - humanize

test:
  imports:
    - kastore

  commands:
    - kastore --help

about:
  home: http://github.com/kastore/kastore
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Write-once-read-many key-array store
  description: Simple key-value store for arrays of numerical data.
  doc_url: 'http://kastore.readthedocs.io/en/stable'
  dev_url: 'https://github.com/tskit-dev/kastore'

extra:
  recipe-maintainers:
    - jeromekelleher
