{% set name = "kastore" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 00d90fe3e3dded1dfa0845fbf1245bc2c14d28bd6004db16a621f02a18f81787

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - kastore=kastore.__main__:main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    # Support for osx_arm64 as per
    # https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/#how-to-add-a-osx-arm64-build-to-a-feedstock
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
  host:
    - setuptools
    - python
    - pip
    - numpy
  run:
    - setuptools
    - python
    - importlib_metadata
    - humanize

test:
  imports:
    - kastore

  commands:
    - kastore --help

about:
  home: http://github.com/kastore/kastore
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Write-once-read-many key-array store
  description: Simple key-value store for arrays of numerical data.
  doc_url: http://kastore.readthedocs.io/en/stable
  dev_url: https://github.com/tskit-dev/kastore

extra:
  recipe-maintainers:
    - jeromekelleher
    - benjeffery
