appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: i5FjKuxhgXFvD8m0iCtNFGExxZDJVto4OIHqICyInpCyqNhDJm1SH4WjwizKqvVZJHO+sJmztZe1xEKZrktKZhvjnKax93nvHKgOHz4MsEcM/0JM4QjqDkB/xXdbiNKWHY+cDRg2QYxcvvt2s9dX3ngWEOjqeGttF5N2FxWoRVhcm15VWiROK/C2WUwmYvKhZsz1dkR+JBClWKbIqeP4R7HDYiixkjhIxfX58/Crt/x7Q4WwxwiupiFL0VbvkuD+Cka9nsIGE7sG1fHBiLqpLT+IC0eowia2nLVR43/Ihw0wNugoLF5Bkbq535yjIUj8aJcWl37UmL9l+pO3MNBP/+LxdS3/GsvzRBhBfGznMkT5qtYizFOJjWS9YNOEL58oCfnLWwFdwMDXwbm4U93kPIlddfog3IrjIS5mjM0UviAotBlnfUWwpytrU3mYWgNqJdpEDjpqWBBIZWTKzMfWc1aUDaU1F4rSKNUNuAdZ2aN3iiyjT/G0XNDIiAUOH+ISs6kQIkmFKCHPUWtPPw3JGHX9bZcHaxsBT7Z+IrQJW602tKOd/f0N1Lp+CTtyDelrqOnW40GxsWiXtUVs8If4+AIs0Y1WEQ+BrrVsdZsfBvVZMOz+34+ATejMzHdwqmMYdtZxqZdV+35pQHnLoUgOAKLL8Ud5tgNF4Trt04rSvcs=}
provider:
  win: azure
conda_forge_output_validation: true
